title: Perfana documentation
description: Documentation for Perfana, the continous performance testing dashboard
baseurl: "/perfana-docs" # the subpath of your site, e.g. /blog
url: "https://perfana.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# remote_theme: pmarsceill/just-the-docs
theme: just-the-docs

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Perfana.io":
    - "//perfana.io"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2019-2020 Perfana Software BV"

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-2709176-10

plugins:
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
